[workspace]
members = ["crates/source_map_parser", "crates/node_sdk"]
resolver = "2"

[workspace.package]
authors = ["MasonChow"]
description = "High performance Source Map stack trace parser & mapper (Rust + WASM)"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = 3
debug = false
